# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/gpt_proto/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client.gpt_proto import gpt_request_pb2 as client_dot_gpt__proto_dot_gpt__request__pb2
from client.gpt_proto import gpt_response_pb2 as client_dot_gpt__proto_dot_gpt__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63lient/gpt_proto/service.proto\x12\x0bgpt.service\x1a\"client/gpt_proto/gpt_request.proto\x1a#client/gpt_proto/gpt_response.proto2H\n\tGPTStudio\x12;\n\tGPTStudio\x12\x14.gpt.request.Request\x1a\x16.gpt.response.Response\"\x00\x42\x03\xf8\x01\x01\x62\x06proto3')



_GPTSTUDIO = DESCRIPTOR.services_by_name['GPTStudio']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _GPTSTUDIO._serialized_start=120
  _GPTSTUDIO._serialized_end=192
# @@protoc_insertion_point(module_scope)
