# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from client.gpt_proto import gpt_request_pb2 as client_dot_gpt__proto_dot_gpt__request__pb2
from client.gpt_proto import gpt_response_pb2 as client_dot_gpt__proto_dot_gpt__response__pb2


class GPTStudioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GPTStudio = channel.unary_unary(
                '/gpt.service.GPTStudio/GPTStudio',
                request_serializer=client_dot_gpt__proto_dot_gpt__request__pb2.Request.SerializeToString,
                response_deserializer=client_dot_gpt__proto_dot_gpt__response__pb2.Response.FromString,
                )


class GPTStudioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GPTStudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GPTStudioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GPTStudio': grpc.unary_unary_rpc_method_handler(
                    servicer.GPTStudio,
                    request_deserializer=client_dot_gpt__proto_dot_gpt__request__pb2.Request.FromString,
                    response_serializer=client_dot_gpt__proto_dot_gpt__response__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gpt.service.GPTStudio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GPTStudio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GPTStudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gpt.service.GPTStudio/GPTStudio',
            client_dot_gpt__proto_dot_gpt__request__pb2.Request.SerializeToString,
            client_dot_gpt__proto_dot_gpt__response__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
